openapi: 3.0.0
info:
  title: Recruitment's Public API
  description: Collection of Public API for 3rd party integration with ELMO's Recruitment.
  version: v1
servers:
  - url: https://[tenant].elmotalent.com.au/api/recruitment/v1
paths:
  /candidates:
    get:
      tags:
        - Candidates
      summary: Get a list of candidates
      description: Get a list of candidates
      operationId: getCandidates
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
        - name: itemsPerPage
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
        - name: id
          in: query
          description: Candidate ID
          required: false
          schema:
            type: string
        - name: firstName
          in: query
          description: Candidate's first name
          required: false
          schema:
            type: string
        - name: lastName
          in: query
          description: Candidate's last name
          required: false
          schema:
            type: string
        - name: email
          in: query
          description: Candidate's email
          required: false
          schema:
            type: string
        - name: homePhone
          in: query
          description: Candidate's home phone
          required: false
          schema:
            type: string
        - name: mobile
          in: query
          description: Candidate's mobile
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of candidates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateListResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsGetResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGetResponse'
components:
  schemas:
    CandidateQuery:
      type: object
      properties:
        id:
          type: string
          example: '10'
        firstName:
          type: string
          example: John
          minLength: 3
          maxLength: 255
        lastName:
          type: string
          example: Doe
          minLength: 3
          maxLength: 255
        email:
          type: string
          example: john.doe@noreply.com
          format: email
          maxLength: 60
        addressLine1:
          type: string
          maxLength: 255
        addressLine2:
          type: string
          maxLength: 255
        suburb:
          type: string
          maxLength: 255
        state:
          type: string
          maxLength: 255
        postcode:
          type: string
          maxLength: 30
        country:
          type: string
          maxLength: 30
        homePhone:
          type: string
          maxLength: 30
        mobile:
          type: string
          maxLength: 30
        education:
          type: array
          items:
            $ref: '#/components/schemas/EducationQuery'
        languages:
          type: array
          items:
            $ref: '#/components/schemas/LanguageQuery'
        experience:
          type: array
          items:
            $ref: '#/components/schemas/ExperienceQuery'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/SkillQuery'
    EducationQuery:
      type: object
      properties:
        id:
          type: string
        school:
          type: string
        degree:
          type: string
        grade:
          type: string
        fieldOfStudy:
          type: string
        activities:
          type: string
        description:
          type: string
        startDateYear:
          type: integer
        endDateYear:
          type: integer
    LanguageQuery:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
        name:
          type: string
        ratingSpeaking:
          type: integer
        ratingReading:
          type: integer
        ratingWriting:
          type: integer
    ExperienceQuery:
      type: object
      properties:
        id:
          type: string
        positionTitle:
          type: string
        companyName:
          type: string
        companyAddress:
          type: string
        startDateMonth:
          type: integer
        startDateYear:
          type: integer
        endDateMonth:
          type: integer
        endDateYear:
          type: integer
        isCurrent:
          type: boolean
    SkillQuery:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    ErrorGetResponse:
      type: object
      properties:
        type:
          type: integer
        error:
          type: string
        status:
          type: string
        message:
          type: string
        instance:
          type: string
    ErrorsGetResponse:
      type: object
      properties:
        type:
          type: integer
        errors:
          type: array
          items:
            type: string
        status:
          type: string
        message:
          type: string
        instance:
          type: string
    ScreeningQuestionQuery:
      type: object
      properties:
        questionId:
          type: string
        question:
          type: string
        questionType:
          $ref: '#/components/schemas/EnumQuestionTypes'
        answerValue:
          type: string
        answerText:
          type: string
    EnumQuestionTypes:
      type: string
      enum:
        - TEXT
        - DATE
        - SELECT
        - MULTISELECT
        - FILE
    Pagination:
      type: object
      properties:
        page:
          type: integer
        itemsPerPage:
          type: integer
        totalItems:
          type: integer
    MetadataListQuery:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
    CandidateListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CandidateQuery'
        metadata:
          $ref: '#/components/schemas/MetadataListQuery'

